# Generated by Django 4.2.5 on 2024-01-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0014_alter_address_latitude_alter_address_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=9, null=True
            ),
        ),
    ]
