# Generated by Django 4.2.5 on 2024-01-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0015_alter_address_latitude_alter_address_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "Carrer"), (2, "Owner"), (3, "Admin")],
                default=2,
                null=True,
            ),
        ),
    ]
