# Generated by Django 4.2.5 on 2023-10-18 20:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("animals", "0017_alter_animal_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimalCare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023,
                            10,
                            18,
                            20,
                            57,
                            42,
                            554588,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023,
                            10,
                            18,
                            20,
                            57,
                            42,
                            554802,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                (
                    "animals",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="animals.animal",
                        verbose_name="animal_care_animals",
                    ),
                ),
                (
                    "carrer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="animal_care_carrer",
                    ),
                ),
            ],
        ),
    ]
