# Generated by Django 4.2.5 on 2023-10-18 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animal_care", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="animalcare", old_name="animals", new_name="animal",
        ),
        migrations.AlterField(
            model_name="animalcare",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 18, 22, 16, 14, 683851, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="animalcare",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 18, 22, 16, 14, 683627, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
