# Generated by Django 4.2.5 on 2023-11-15 11:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0018_alter_animal_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("animal_care", "0009_alter_animalcare_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animalcare",
            name="animal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="animals.animal",
                verbose_name="animal_care_animals",
            ),
        ),
        migrations.AlterField(
            model_name="animalcare",
            name="carrer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
                verbose_name="animal_care_carrer",
            ),
        ),
        migrations.AlterField(
            model_name="animalcare",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 15, 11, 59, 1, 745763, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="animalcare",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 15, 11, 59, 1, 745552, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
