# Generated by Django 4.2.5 on 2023-11-26 08:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "animal_care",
            "0010_alter_animalcare_animal_alter_animalcare_carrer_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="animalcare",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Ongoing", "Ongoing"),
                    ("Finished", "Finished"),
                ],
                default=("New", "New"),
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="animalcare",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 26, 8, 38, 24, 438040, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="animalcare",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 26, 8, 38, 24, 437852, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Proposed", "Proposed"),
                            ("Accepted", "Accepted"),
                            ("Declined", "Declined"),
                        ],
                        default=("Proposed", "Proposed"),
                        max_length=15,
                    ),
                ),
                (
                    "carrer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="animalcare",
            name="offers",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="animal_care.offer",
            ),
        ),
    ]
