# Generated by Django 4.2.5 on 2023-11-28 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animal_care", "0011_animalcare_status_alter_animalcare_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animalcare",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 28, 12, 43, 36, 491511, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="animalcare",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 28, 12, 43, 36, 491305, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
