# Generated by Django 4.2.5 on 2023-11-30 23:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "animal_care",
            "0013_alter_animalcare_carrer_alter_animalcare_end_date_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="animalcare", name="offers",),
        migrations.AddField(
            model_name="offer",
            name="animal_care",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="animal_care.animalcare",
            ),
        ),
        migrations.AlterField(
            model_name="animalcare",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 30, 23, 19, 12, 626197, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="animalcare",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 30, 23, 19, 12, 626012, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
