# Generated by Django 4.2.5 on 2024-01-15 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0021_alter_animal_size"),
        ("animal_care", "0028_alter_animalcare_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="animalcare",
            name="animals",
            field=models.ManyToManyField(
                related_name="animal_cares", to="animals.animal"
            ),
        ),
        migrations.AlterField(
            model_name="animalcare",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 15, 22, 8, 43, 33883, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="animalcare",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 15, 22, 8, 43, 33669, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.DeleteModel(name="AnimalCarePets",),
    ]
