# Generated by Django 4.2.5 on 2024-02-13 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animal_care", "0033_alter_animalcare_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="animalcare",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="animalcare",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 13, 15, 43, 33, 923458, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="animalcare",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 13, 15, 43, 33, 923271, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
