# Generated by Django 4.2.5 on 2024-02-13 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "animal_care",
            "0035_alter_animalcare_end_date_alter_animalcare_price_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="animalcare",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 13, 15, 48, 55, 766924, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="animalcare",
            name="price",
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="animalcare",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 13, 15, 48, 55, 766678, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
