# Generated by Django 4.2.5 on 2024-02-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "animal_care",
            "0049_alter_animalcare_end_date_alter_animalcare_price_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="animalcare",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Ongoing", "Ongoing"),
                    ("Finished", "Finished"),
                ],
                default="New",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="status",
            field=models.CharField(
                choices=[
                    ("Proposed", "Proposed"),
                    ("Accepted", "Accepted"),
                    ("Declined", "Declined"),
                ],
                default="Proposed",
                max_length=15,
            ),
        ),
    ]
