# Generated by Django 4.2.5 on 2024-02-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animal_care", "0050_alter_animalcare_status_alter_offer_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer", name="viewed", field=models.BooleanField(default=False),
        ),
    ]
