# Generated by Django 4.2.5 on 2023-09-29 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0003_alter_animal_specie"),
    ]

    operations = [
        migrations.RenameField(
            model_name="animal", old_name="specie", new_name="species",
        ),
    ]
