# Generated by Django 4.2.5 on 2023-09-30 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("animals", "0004_rename_specie_animal_species"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="species",
            field=models.CharField(
                choices=[("Dog", "Dog"), ("Cat", "Cat")],
                default=("Dog", "Dog"),
                max_length=10,
            ),
        ),
    ]
