# Generated by Django 4.2.5 on 2023-09-30 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0007_alter_animal_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="CareInstructions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_of_walks_per_day",
                    models.IntegerField(
                        default=3, verbose_name="Number of walks per day"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="animal",
            name="care_instructions",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="animals.careinstructions",
            ),
        ),
    ]
