# Generated by Django 4.2.5 on 2023-09-30 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0009_alter_careinstructions_options"),
    ]

    operations = [
        migrations.AlterModelOptions(name="animal", options={"verbose_name": "pizza"},),
    ]
