# Generated by Django 4.2.5 on 2023-09-30 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0010_alter_animal_options"),
    ]

    operations = [
        migrations.AlterModelOptions(name="animal", options={},),
        migrations.AlterModelOptions(name="careinstructions", options={},),
    ]
