# Generated by Django 4.2.5 on 2023-09-30 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0011_alter_animal_options_alter_careinstructions_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="careinstructions", options={"verbose_name": "Care Instructions"},
        ),
        migrations.AlterField(
            model_name="animal",
            name="care_instructions",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="animals.careinstructions",
            ),
        ),
    ]
