# Generated by Django 4.2.5 on 2023-09-30 16:42

import animals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0012_alter_careinstructions_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="careinstructions",
            name="number_of_walks_per_day",
            field=models.IntegerField(
                default=3,
                validators=[animals.models.validate_number_of_walks],
                verbose_name="Number of walks per day",
            ),
        ),
    ]
