# Generated by Django 4.2.5 on 2023-09-30 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("animals", "0013_alter_careinstructions_number_of_walks_per_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="care_instructions",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="animals.careinstructions",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
