# Generated by Django 4.2.5 on 2023-09-30 21:30

import animals.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0015_alter_animal_care_instructions_alter_animal_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="care_instructions",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="animals.careinstructions",
            ),
        ),
        migrations.AlterField(
            model_name="careinstructions",
            name="number_of_walks_per_day",
            field=models.IntegerField(
                blank=True,
                default=3,
                null=True,
                validators=[animals.models.validate_number_of_walks],
                verbose_name="Number of walks per day",
            ),
        ),
    ]
