# Generated by Django 4.2.5 on 2023-11-30 22:29

import animals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0018_alter_animal_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="size",
            field=models.CharField(
                choices=[
                    ("Small", "Small"),
                    ("Medium", "Medium"),
                    ("Large", "Large"),
                    ("Very Large", "Very Large"),
                ],
                max_length=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="weight",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=150, null=True
            ),
        ),
        migrations.AddField(
            model_name="careinstructions",
            name="additional_instructions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="careinstructions",
            name="food_amount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="careinstructions",
            name="food_portions",
            field=models.IntegerField(blank=True, default=3),
        ),
        migrations.AlterField(
            model_name="careinstructions",
            name="number_of_walks_per_day",
            field=models.IntegerField(
                blank=True,
                default=3,
                validators=[animals.models.validate_number_of_walks],
                verbose_name="Number of walks per day",
            ),
        ),
    ]
