# Generated by Django 4.2.5 on 2023-12-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0019_animal_size_animal_weight_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Small", "Small"),
                    ("Medium", "Medium"),
                    ("Large", "Large"),
                    ("Very Large", "Very Large"),
                ],
                max_length=12,
                null=True,
            ),
        ),
    ]
