# Generated by Django 4.2.5 on 2024-01-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0020_alter_animal_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Small", "Small"),
                    ("Medium", "Medium"),
                    ("Big", "Big"),
                    ("Very Big", "Very Big"),
                ],
                max_length=12,
                null=True,
            ),
        ),
    ]
