# Generated by Django 4.2.5 on 2024-01-30 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("animals", "0021_alter_animal_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="animals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
