# Generated by Django 4.2.5 on 2024-02-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0023_alter_animal_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="weight",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
    ]
