# Generated by Django 4.2.5 on 2024-03-04 19:58

import animals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0024_alter_animal_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="image",
            field=models.ImageField(blank=True, upload_to=animals.models.file_location),
        ),
    ]
