# Generated by Django 4.2.5 on 2024-04-09 09:12

import animals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0025_animal_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=animals.models.file_location
            ),
        ),
    ]
